pub const EMOJIS: &[(&str, &str)] = &[
    ("👩‍👩‍👧‍👧", "family mothers two girls"),
    ("👩‍👩‍👧‍👦", "family mothers children"),
    ("👩‍👩‍👦‍👦", "family mothers two boys"),
    ("👨‍👩‍👧‍👧", "family two girls"),
    ("👨‍👩‍👧‍👦", "family children"),
    ("👨‍👩‍👦‍👦", "family two boys"),
    ("👨‍👨‍👧‍👧", "family fathers two girls"),
    ("👨‍👨‍👧‍👦", "family fathers children"),
    ("👨‍👨‍👦‍👦", "family fathers two boys"),
    ("👩‍👩‍👧", "family mothers one girl"),
    ("👩‍👩‍👦", "family mothers one boy"),
    ("👩‍👧‍👧", "single mother two girls"),
    ("👩‍👧‍👦", "single mother two children"),
    ("👩‍👦‍👦", "single mother two boys"),
    ("👨‍👩‍👧", "family one girl"),
    ("👨‍👨‍👧", "family fathers one girl"),
    ("👨‍👨‍👦", "family fathers one boy"),
    ("👨‍👧‍👧", "single father two girls"),
    ("👨‍👧‍👦", "single father with children"),
    ("👨‍👦‍👦", "single father two boys"),
    ("👩‍👧", "single mother one girl"),
    ("👩‍👦", "single mother one boy"),
    ("👨‍👧", "single father one girl"),
    ("👨‍👦", "single father one boy"),
    ("😂", "joy"),
    ("❤️", "heart"),
    ("😍", "heart eyes"),
    ("😭", "sob"),
    ("😊", "blush"),
    ("😒", "unamused"),
    ("😘", "kissing heart"),
    ("💕", "two hearts"),
    ("☺️", "white smiling face"),
    ("😩", "weary"),
    ("👌", "ok hand"),
    ("😔", "pensive"),
    ("😏", "smirk"),
    ("😁", "grin"),
    ("♻", "recycle"),
    ("😉", "wink"),
    ("👍", "thumbsup"),
    ("🙏", "pray"),
    ("😌", "relieved"),
    ("🎶", "notes"),
    ("😳", "flushed"),
    ("🙌", "raised hands"),
    ("🙈", "see no evil"),
    ("😢", "cry"),
    ("😎", "sunglasses"),
    ("✌️", "v"),
    ("👀", "eyes"),
    ("😅", "sweat smile"),
    ("✨", "sparkles"),
    ("😴", "sleeping"),
    ("😄", "smile"),
    ("💜", "purple heart"),
    ("💔", "broken heart"),
    ("💯", "100"),
    ("😑", "expressionless"),
    ("💖", "sparkling heart"),
    ("💙", "blue heart"),
    ("😕", "confused"),
    ("💁", "information desk person"),
    ("😜", "stuck out tongue winking eye"),
    ("😞", "disappointed"),
    ("😋", "yum"),
    ("😐", "neutral face"),
    ("😪", "sleepy"),
    ("👏", "clap"),
    ("💘", "cupid"),
    ("💗", "heartpulse"),
    ("💞", "revolving hearts"),
    ("⬅️", "arrow left"),
    ("🙊", "speak no evil"),
    ("💋", "kiss"),
    ("👉", "point right"),
    ("🌸", "cherry blossom"),
    ("😱", "scream"),
    ("🔥", "fire"),
    ("😡", "rage"),
    ("😃", "smiley"),
    ("🎉", "tada"),
    ("😫", "tired face"),
    ("📷", "camera"),
    ("🌹", "rose"),
    ("😝", "stuck out tongue closed eyes"),
    ("💪", "muscle"),
    ("💀", "skull"),
    ("☀️", "sunny"),
    ("💛", "yellow heart"),
    ("😤", "triumph"),
    ("🌚", "new moon with face"),
    ("😆", "laughing"),
    ("😓", "sweat"),
    ("👈", "point left"),
    ("✔️", "heavy check mark"),
    ("😻", "heart eyes cat"),
    ("😀", "grinning"),
    ("😷", "mask"),
    ("💚", "green heart"),
    ("👋", "wave"),
    ("😣", "persevere"),
    ("💓", "heartbeat"),
    ("▶️", "arrow forward"),
    ("◀️", "arrow backward"),
    ("↪️", "arrow right hook"),
    ("↩️", "leftwards arrow with hook"),
    ("👑", "crown"),
    ("😚", "kissing closed eyes"),
    ("😛", "stuck out tongue"),
    ("😥", "disappointed relieved"),
    ("😇", "innocent"),
    ("🎧", "headphones"),
    ("✅", "white check mark"),
    ("😖", "confounded"),
    ("➡", "arrow right"),
    ("😠", "angry"),
    ("😬", "grimacing"),
    ("🌟", "star2"),
    ("🔫", "gun"),
    ("🙋", "raising hand"),
    ("👎", "thumbsdown"),
    ("💃", "dancer"),
    ("🎵", "musical note"),
    ("😶", "no mouth"),
    ("💫", "dizzy"),
    ("✊", "fist"),
    ("👇", "point down"),
    ("🔴", "red circle"),
    ("🙅", "no good"),
    ("💥", "boom"),
    ("💭", "thought balloon"),
    ("👅", "tongue"),
    ("💩", "Pile of Poo"),
    ("😰", "cold sweat"),
    ("💎", "gem"),
    ("🙆", "ok woman"),
    ("🍕", "pizza"),
    ("😹", "joy cat"),
    ("🌞", "sun with face"),
    ("🍃", "leaves"),
    ("💦", "sweat drops"),
    ("🐧", "penguin"),
    ("💤", "zzz"),
    ("🚶", "walking"),
    ("✈️", "airplane"),
    ("🎈", "balloon"),
    ("⭐", "star"),
    ("🎀", "ribbon"),
    ("☑️", "ballot box with check"),
    ("😟", "worried"),
    ("🔞", "underage"),
    ("😨", "fearful"),
    ("🍀", "four leaf clover"),
    ("🌺", "hibiscus"),
    ("🎤", "microphone"),
    ("👐", "open hands"),
    ("👻", "ghost"),
    ("🌴", "palm tree"),
    ("‼️", "bangbang"),
    ("💅", "nail care"),
    ("❌", "x"),
    ("👽", "alien"),
    ("🙇", "bow"),
    ("☁", "cloud"),
    ("⚽", "soccer"),
    ("👼", "angel"),
    ("👯", "dancers"),
    ("❗", "exclamation"),
    ("❄️", "snowflake"),
    ("☝️", "point up"),
    ("😙", "kissing smiling eyes"),
    ("🌈", "rainbow"),
    ("🌙", "crescent moon"),
    ("💟", "heart decoration"),
    ("💝", "gift heart"),
    ("🎁", "gift"),
    ("🍻", "beers"),
    ("😧", "anguished"),
    ("🌍", "earth africa"),
    ("🎥", "movie camera"),
    ("⚓", "anchor"),
    ("⚡", "zap"),
    ("✖️", "heavy multiplication x"),
    ("🏃", "runner"),
    ("🌻", "sunflower"),
    ("🌎", "earth americas"),
    ("💐", "bouquet"),
    ("🐶", "dog"),
    ("💰", "moneybag"),
    ("🌿", "herb"),
    ("👫", "couple"),
    ("🍂", "fallen leaf"),
    ("🌷", "tulip"),
    ("🎂", "birthday"),
    ("🐱", "cat"),
    ("☕", "coffee"),
    ("😵", "dizzy face"),
    ("👆", "point up 2"),
    ("😮", "open mouth"),
    ("😯", "hushed"),
    ("🏀", "basketball"),
    ("🎄", "christmas tree"),
    ("💍", "ring"),
    ("🌝", "full moon with face"),
    ("😲", "astonished"),
    ("👭", "two women holding hands"),
    ("💸", "money with wings"),
    ("😿", "crying cat face"),
    ("🙉", "hear no evil"),
    ("💨", "dash"),
    ("🌵", "cactus"),
    ("♨️", "hotsprings"),
    ("☎️", "telephone"),
    ("🍁", "maple leaf"),
    ("👸", "princess"),
    ("💆", "massage"),
    ("💌", "love letter"),
    ("🏆", "trophy"),
    ("🙍", "person frowning"),
    ("🇺🇸", "United States of America"),
    ("🎊", "confetti ball"),
    ("🌼", "blossom"),
    ("👄", "lips"),
    ("🍟", "fries"),
    ("🍩", "doughnut"),
    ("😦", "frowning"),
    ("🌊", "ocean"),
    ("💣", "bomb"),
    ("🆗", "ok"),
    ("🌀", "cyclone"),
    ("🚀", "rocket"),
    ("☔", "umbrella"),
    ("💏", "couplekiss"),
    ("👩‍❤️‍💋‍👩", "couple woman kiss"),
    ("👨‍❤️‍💋‍👨", "couple man kiss"),
    ("💑", "couple with heart"),
    ("👩‍❤️‍👩", "girl girl love"),
    ("👨‍❤️‍👨", "man man love"),
    ("🍭", "lollipop"),
    ("🎬", "clapper"),
    ("🐷", "pig"),
    ("😈", "smiling imp"),
    ("👿", "imp"),
    ("🐝", "bee"),
    ("😽", "kissing cat"),
    ("💢", "anger"),
    ("🎼", "musical score"),
    ("🎅", "santa"),
    ("🌏", "earth asia"),
    ("🏈", "football"),
    ("🎸", "guitar"),
    ("🐼", "panda face"),
    ("💬", "speech balloon"),
    ("🍓", "strawberry"),
    ("😼", "smirk cat"),
    ("🍌", "banana"),
    ("🍉", "watermelon"),
    ("⛄", "snowman"),
    ("😸", "smile cat"),
    ("🔝", "top"),
    ("🍆", "eggplant"),
    ("🔮", "crystal ball"),
    ("🍴", "fork and knife"),
    ("📲", "calling"),
    ("📱", "iphone"),
    ("⛅", "partly sunny"),
    ("⚠️", "warning"),
    ("🙀", "scream cat"),
    ("🔸", "small orange diamond"),
    ("👶", "baby"),
    ("🐾", "feet"),
    ("👣", "footprints"),
    ("🍺", "beer"),
    ("🍷", "wine glass"),
    ("⭕", "o"),
    ("📹", "video camera"),
    ("🐰", "rabbit"),
    ("🍹", "tropical drink"),
    ("🚬", "smoking"),
    ("👾", "space invader"),
    ("🍑", "peach"),
    ("🐍", "snake"),
    ("🐢", "turtle"),
    ("🍒", "cherries"),
    ("😗", "kissing"),
    ("🐸", "frog"),
    ("🌌", "milky way"),
    ("🚨", "rotating light"),
    ("🐣", "hatching chick"),
    ("📕", "closed book"),
    ("🍬", "candy"),
    ("🍔", "hamburger"),
    ("🐻", "bear"),
    ("🐯", "tiger"),
    ("⏩", "fast forward"),
    ("🍦", "icecream"),
    ("🍍", "pineapple"),
    ("🌾", "ear of rice"),
    ("💉", "syringe"),
    ("🚮", "put litter in its place"),
    ("🍫", "chocolate bar"),
    ("▪️", "black small square"),
    ("📺", "tv"),
    ("💊", "pill"),
    ("🐙", "octopus"),
    ("🎃", "jack o lantern"),
    ("🍇", "grapes"),
    ("😺", "smiley cat"),
    ("💿", "cd"),
    ("🍸", "cocktail"),
    ("🍰", "cake"),
    ("🎮", "video game"),
    ("⬇️", "arrow down"),
    ("🚫", "no entry sign"),
    ("💄", "lipstick"),
    ("🐳", "whale"),
    ("🍪", "cookie"),
    ("🐬", "dolphin"),
    ("🔊", "loud sound"),
    ("👨", "man"),
    ("🐥", "hatched chick"),
    ("🐒", "monkey"),
    ("📚", "books"),
    ("👹", "japanese ogre"),
    ("💂", "guardsman"),
    ("📢", "loudspeaker"),
    ("✂️", "scissors"),
    ("👧", "girl"),
    ("🎓", "mortar board"),
    ("🇫🇷", "France"),
    ("⚾️", "baseball"),
    ("🚦", "vertical traffic light"),
    ("👩", "woman"),
    ("🎆", "fireworks"),
    ("🌠", "stars"),
    ("🆘", "sos"),
    ("🍄", "mushroom"),
    ("😾", "pouting cat"),
    ("🛅", "left luggage"),
    ("👠", "high heel"),
    ("🎯", "dart"),
    ("🏊", "swimmer"),
    ("🔑", "key"),
    ("👙", "bikini"),
    ("👪", "family"),
    ("✏", "pencil2"),
    ("🐘", "elephant"),
    ("💧", "droplet"),
    ("🌱", "seedling"),
    ("🍎", "apple"),
    ("🆒", "cool"),
    ("📞", "telephone receiver"),
    ("💵", "dollar"),
    ("🏡", "house with garden"),
    ("📖", "book"),
    ("💇", "haircut"),
    ("💻", "computer"),
    ("💡", "bulb"),
    ("❓", "question"),
    ("🔙", "back"),
    ("👦", "boy"),
    ("🔐", "closed lock with key"),
    ("🙎", "person with pouting face"),
    ("🍊", "tangerine"),
    ("🌅", "sunrise"),
    ("🍗", "poultry leg"),
    ("🔵", "blue circle"),
    ("🚘", "oncoming automobile"),
    ("🍧", "shaved ice"),
    ("🇮🇹", "Italy"),
    ("🐦", "bird"),
    ("🇬🇧", "Great Britain"),
    ("🌛", "first quarter moon with face"),
    ("👓", "eyeglasses"),
    ("🐐", "goat"),
    ("🌃", "night with stars"),
    ("👵", "older woman"),
    ("⚫", "black circle"),
    ("🌑", "new moon"),
    ("👬", "two men holding hands"),
    ("⚪", "white circle"),
    ("🛃", "customs"),
    ("🐠", "tropical fish"),
    ("🏠", "house"),
    ("🔃", "arrows clockwise"),
    ("🌜", "last quarter moon with face"),
    ("📍", "round pushpin"),
    ("🌕", "full moon"),
    ("👟", "athletic shoe"),
    ("🍋", "lemon"),
    ("🍼", "baby bottle"),
    ("🍝", "spaghetti"),
    ("🎐", "wind chime"),
    ("🍥", "fish cake"),
    ("🌲", "evergreen tree"),
    ("🆙", "up"),
    ("⬆️", "arrow up"),
    ("↗️", "arrow upper right"),
    ("↘️", "arrow lower right"),
    ("↙️", "arrow lower left"),
    ("🎭", "performing arts"),
    ("👃", "nose"),
    ("🐽", "pig nose"),
    ("🐟", "fish"),
    ("👳", "man with turban"),
    ("🐨", "koala"),
    ("👂", "ear"),
    ("✳️", "eight spoked asterisk"),
    ("🔹", "small blue diamond"),
    ("🚿", "shower"),
    ("🐛", "bug"),
    ("🍜", "ramen"),
    ("🎩", "tophat"),
    ("👰", "bride with veil"),
    ("⛽", "fuelpump"),
    ("🏁", "checkered flag"),
    ("🐴", "horse"),
    ("⌚", "watch"),
    ("🐵", "monkey face"),
    ("🚼", "baby symbol"),
    ("🆕", "new"),
    ("🆓", "free"),
    ("🎇", "sparkler"),
    ("🌽", "corn"),
    ("🎾", "tennis"),
    ("⏰", "alarm clock"),
    ("🔋", "battery"),
    ("❕", "grey exclamation"),
    ("🐺", "wolf"),
    ("🗿", "moyai"),
    ("🐮", "cow"),
    ("📣", "mega"),
    ("👴", "older man"),
    ("👗", "dress"),
    ("🔗", "link"),
    ("🐔", "chicken"),
    ("🐋", "whale2"),
    ("↖", "arrow upper left"),
    ("🌳", "deciduous tree"),
    ("🍱", "bento"),
    ("📌", "pushpin"),
    ("🔜", "soon"),
    ("🔁", "repeat"),
    ("🐉", "dragon"),
    ("🐹", "hamster"),
    ("⛳", "golf"),
    ("🏄", "surfer"),
    ("🐭", "mouse"),
    ("🌒", "waxing crescent moon"),
    ("🚙", "blue car"),
    ("🅰️", "a"),
    ("⁉️", "interrobang"),
    ("🈹", "u5272"),
    ("🔌", "electric plug"),
    ("🌓", "first quarter moon"),
    ("♋", "cancer"),
    ("🔱", "trident"),
    ("🍞", "bread"),
    ("👮", "cop"),
    ("🍵", "tea"),
    ("🎣", "fishing pole and fish"),
    ("🚲", "bike"),
    ("🍚", "rice"),
    ("📻", "radio"),
    ("🐤", "baby chick"),
    ("⤵️", "arrow heading down"),
    ("🌘", "waning crescent moon"),
    ("↕", "arrow up down"),
    ("🌗", "last quarter moon"),
    ("🔘", "radio button"),
    ("🐑", "sheep"),
    ("👱", "person with blond hair"),
    ("🌖", "waning gibbous moon"),
    ("🔒", "lock"),
    ("🍏", "green apple"),
    ("👺", "japanese goblin"),
    ("➰", "curly loop"),
    ("🚩", "triangular flag on post"),
    ("🔄", "arrows counterclockwise"),
    ("🐎", "racehorse"),
    ("🍤", "fried shrimp"),
    ("🌄", "sunrise over mountains"),
    ("🌋", "volcano"),
    ("🐓", "rooster"),
    ("📥", "inbox tray"),
    ("💒", "wedding"),
    ("🍣", "sushi"),
    ("〰", "wavy dash"),
    ("🍨", "ice cream"),
    ("⏪", "rewind"),
    ("🍅", "tomato"),
    ("🐇", "rabbit2"),
    ("✴️", "eight pointed black star"),
    ("🔺", "small red triangle"),
    ("🔆", "high brightness"),
    ("➕", "heavy plus sign"),
    ("👲", "man with gua pi mao"),
    ("🏪", "convenience store"),
    ("👥", "busts in silhouette"),
    ("🐞", "beetle"),
    ("🔻", "small red triangle down"),
    ("🇩🇪", "Germany"),
    ("⤴️", "arrow heading up"),
    ("📛", "name badge"),
    ("🛀", "bath"),
    ("⛔", "no entry"),
    ("🐊", "crocodile"),
    ("🐕", "dog2"),
    ("🐈", "cat2"),
    ("🔨", "hammer"),
    ("🍖", "meat on bone"),
    ("🐚", "shell"),
    ("❇️", "sparkle"),
    ("🅱️", "b"),
    ("Ⓜ️", "m"),
    ("🐩", "poodle"),
    ("♒", "aquarius"),
    ("🍲", "stew"),
    ("👖", "jeans"),
    ("🍯", "honey pot"),
    ("🎹", "musical keyboard"),
    ("🔓", "unlock"),
    ("✒", "black nib"),
    ("🗽", "statue of liberty"),
    ("💲", "heavy dollar sign"),
    ("🏂", "snowboarder"),
    ("💮", "white flower"),
    ("👔", "necktie"),
    ("💠", "diamond shape with a dot inside"),
    ("♈", "aries"),
    ("🚺", "womens"),
    ("🐜", "ant"),
    ("♏", "scorpius"),
    ("🌇", "city sunset"),
    ("⏳", "hourglass flowing sand"),
    ("🅾️", "o2"),
    ("🐲", "dragon face"),
    ("🐌", "snail"),
    ("📀", "dvd"),
    ("👕", "shirt"),
    ("🎲", "game die"),
    ("➖", "heavy minus sign"),
    ("🎎", "dolls"),
    ("♐", "sagittarius"),
    ("🎱", "8ball"),
    ("🚌", "bus"),
    ("🍮", "custard"),
    ("🎌", "crossed flags"),
    ("〽️", "part alternation mark"),
    ("🐫", "camel"),
    ("🍛", "curry"),
    ("🚂", "steam locomotive"),
    ("🏥", "hospital"),
    ("🇯🇵", "Japan"),
    ("🔷", "large blue diamond"),
    ("🎋", "tanabata tree"),
    ("🔔", "bell"),
    ("♌", "leo"),
    ("♊", "gemini"),
    ("🍐", "pear"),
    ("🔶", "large orange diamond"),
    ("♉", "taurus"),
    ("🌐", "globe with meridians"),
    ("🚪", "door"),
    ("🕕", "clock6"),
    ("🚔", "oncoming police car"),
    ("📩", "envelope with arrow"),
    ("🌂", "closed umbrella"),
    ("🎷", "saxophone"),
    ("⛪", "church"),
    ("🚴", "bicyclist"),
    ("♓", "pisces"),
    ("🍡", "dango"),
    ("♑", "capricorn"),
    ("🏢", "office"),
    ("🚣", "rowboat"),
    ("👒", "womans hat"),
    ("👞", "mans shoe"),
    ("🏩", "love hotel"),
    ("🗻", "mount fuji"),
    ("🐪", "dromedary camel"),
    ("👜", "handbag"),
    ("⌛", "hourglass"),
    ("❎", "negative squared cross mark"),
    ("🎺", "trumpet"),
    ("🏫", "school"),
    ("🐄", "cow2"),
    ("👷", "construction worker"),
    ("🚽", "toilet"),
    ("🐖", "pig2"),
    ("❔", "grey question"),
    ("🔰", "beginner"),
    ("🎻", "violin"),
    ("🔛", "on"),
    ("💳", "credit card"),
    ("🆔", "id"),
    ("㊙", "secret"),
    ("🎡", "ferris wheel"),
    ("🎳", "bowling"),
    ("♎", "libra"),
    ("♍", "virgo"),
    ("💈", "barber"),
    ("👛", "purse"),
    ("🎢", "roller coaster"),
    ("🐀", "rat"),
    ("📅", "date"),
    ("🏉", "rugby football"),
    ("🐏", "ram"),
    ("🔼", "arrow up small"),
    ("🔲", "black square button"),
    ("📴", "mobile phone off"),
    ("🗼", "tokyo tower"),
    ("㊗", "congratulations"),
    ("👘", "kimono"),
    ("🇷🇺", "Russia"),
    ("🚢", "ship"),
    ("🔎", "mag right"),
    ("🔍", "mag"),
    ("🚒", "fire engine"),
    ("🕦", "clock1130"),
    ("🚓", "police car"),
    ("🃏", "black joker"),
    ("🌉", "bridge at night"),
    ("📦", "package"),
    ("🚖", "oncoming taxi"),
    ("📆", "calendar"),
    ("🏇", "horse racing"),
    ("🐅", "tiger2"),
    ("👢", "boot"),
    ("🚑", "ambulance"),
    ("🔳", "white square button"),
    ("🐗", "boar"),
    ("🎒", "school satchel"),
    ("➿", "loop"),
    ("💷", "pound"),
    ("ℹ", "information source"),
    ("🐂", "ox"),
    ("🍙", "rice ball"),
    ("🆚", "vs"),
    ("🔚", "end"),
    ("🅿️", "parking"),
    ("👡", "sandal"),
    ("⛺", "tent"),
    ("💺", "seat"),
    ("🚕", "taxi"),
    ("◾", "black medium small square"),
    ("💼", "briefcase"),
    ("📰", "newspaper"),
    ("🎪", "circus tent"),
    ("🔯", "six pointed star"),
    ("🚹", "mens"),
    ("🏰", "european castle"),
    ("🔦", "flashlight"),
    ("🌁", "foggy"),
    ("⏫", "arrow double up"),
    ("🎍", "bamboo"),
    ("🎫", "ticket"),
    ("🚁", "helicopter"),
    ("💽", "minidisc"),
    ("🚍", "oncoming bus"),
    ("🍈", "melon"),
    ("▫", "white small square"),
    ("🏤", "european post office"),
    ("🔟", "keycap ten"),
    ("📓", "notebook"),
    ("🔕", "no bell"),
    ("🍢", "oden"),
    ("🎏", "flags"),
    ("🎠", "carousel horse"),
    ("🐡", "blowfish"),
    ("📈", "chart with upwards trend"),
    ("🍠", "sweet potato"),
    ("🎿", "ski"),
    ("🕛", "clock12"),
    ("📶", "signal strength"),
    ("🚧", "construction"),
    ("◼", "black medium square"),
    ("📡", "satellite"),
    ("💶", "euro"),
    ("👚", "womans clothes"),
    ("📒", "ledger"),
    ("🐆", "leopard"),
    ("🔅", "low brightness"),
    ("🕒", "clock3"),
    ("🏬", "department store"),
    ("🚚", "truck"),
    ("🍶", "sake"),
    ("🚃", "railway car"),
    ("🚤", "speedboat"),
    ("🇰🇷", "korea"),
    ("📼", "vhs"),
    ("🕐", "clock1"),
    ("⏬", "arrow double down"),
    ("🐃", "water buffalo"),
    ("🔽", "arrow down small"),
    ("💴", "yen"),
    ("🔇", "mute"),
    ("🎽", "running shirt with sash"),
    ("⬜", "white large square"),
    ("♿", "wheelchair"),
    ("🕑", "clock2"),
    ("📎", "paperclip"),
    ("🏧", "atm"),
    ("🎦", "cinema"),
    ("🔭", "telescope"),
    ("🎑", "rice scene"),
    ("📘", "blue book"),
    ("◻️", "white medium square"),
    ("📮", "postbox"),
    ("📧", "e-mail"),
    ("🐁", "mouse2"),
    ("🚄", "bullettrain side"),
    ("🉐", "ideograph advantage"),
    ("🔩", "nut and bolt"),
    ("🆖", "ng"),
    ("🏨", "hotel"),
    ("🚾", "wc"),
    ("🏮", "izakaya lantern"),
    ("🔂", "repeat one"),
    ("📬", "mailbox with mail"),
    ("📉", "chart with downwards trend"),
    ("📗", "green book"),
    ("🚜", "tractor"),
    ("⛲", "fountain"),
    ("🚇", "metro"),
    ("📋", "clipboard"),
    ("📵", "no mobile phones"),
    ("🕓", "clock4"),
    ("🚭", "no smoking"),
    ("⬛", "black large square"),
    ("🎰", "slot machine"),
    ("🕔", "clock5"),
    ("🛁", "bathtub"),
    ("📜", "scroll"),
    ("🚉", "station"),
    ("🍘", "rice cracker"),
    ("🏦", "bank"),
    ("🔧", "wrench"),
    ("🈯️", "u6307"),
    ("🚛", "articulated lorry"),
    ("📄", "page facing up"),
    ("⛎", "ophiuchus"),
    ("📊", "bar chart"),
    ("🚷", "no pedestrians"),
    ("🇨🇳", "Chinea"),
    ("📳", "vibration mode"),
    ("🕙", "clock10"),
    ("🕘", "clock9"),
    ("🚅", "bullettrain front"),
    ("🚐", "minibus"),
    ("🚊", "tram"),
    ("🕗", "clock8"),
    ("🈳", "u7a7a"),
    ("🚥", "traffic light"),
    ("🚵", "mountain bicyclist"),
    ("🔬", "microscope"),
    ("🏯", "japanese castle"),
    ("🔖", "bookmark"),
    ("📑", "bookmark tabs"),
    ("👝", "pouch"),
    ("🆎", "ab"),
    ("📃", "page with curl"),
    ("🎴", "flower playing cards"),
    ("🕚", "clock11"),
    ("📠", "fax"),
    ("🕖", "clock7"),
    ("◽", "white medium small square"),
    ("💱", "currency exchange"),
    ("🔉", "sound"),
    ("💹", "chart"),
    ("🆑", "cl"),
    ("💾", "floppy disk"),
    ("🏣", "post office"),
    ("🔈", "speaker"),
    ("🗾", "japan"),
    ("🈺", "u55b6"),
    ("🀄", "mahjong"),
    ("📨", "incoming envelope"),
    ("📙", "orange book"),
    ("🚻", "restroom"),
    ("🈚️", "u7121"),
    ("🈶", "u6709"),
    ("📐", "triangular ruler"),
    ("🚋", "train"),
    ("🈸", "u7533"),
    ("🚎", "trolleybus"),
    ("🈷", "u6708"),
    ("🔢", "1234"),
    ("📔", "notebook with decorative cover"),
    ("🈲", "u7981"),
    ("🈵", "u6e80"),
    ("📯", "postal horn"),
    ("🏭", "factory"),
    ("🚸", "children crossing"),
    ("🚆", "train2"),
    ("📏", "straight ruler"),
    ("📟", "pager"),
    ("🉑", "accept"),
    ("🈴", "u5408"),
    ("🔏", "lock with ink pen"),
    ("🕜", "clock130"),
    ("🈂️", "sa"),
    ("📤", "outbox tray"),
    ("🔀", "twisted rightwards arrows"),
    ("📫", "mailbox"),
    ("🚈", "light rail"),
    ("🕤", "clock930"),
    ("🚏", "busstop"),
    ("📂", "open file folder"),
    ("📁", "file folder"),
    ("🚰", "potable water"),
    ("📇", "card index"),
    ("🕝", "clock230"),
    ("🚝", "monorail"),
    ("🕧", "clock1230"),
    ("🕥", "clock1030"),
    ("🔤", "abc"),
    ("📪", "mailbox closed"),
    ("🕟", "clock430"),
    ("🚞", "mountain railway"),
    ("🚯", "do not litter"),
    ("🕞", "clock330"),
    ("➗", "heavy division sign"),
    ("🕢", "clock730"),
    ("🕠", "clock530"),
    ("🔠", "capital abcd"),
    ("📭", "mailbox with no mail"),
    ("🔣", "symbols"),
    ("🚡", "aerial tramway"),
    ("🕣", "clock830"),
    ("🕡", "clock630"),
    ("🔡", "abcd"),
    ("🚠", "mountain cableway"),
    ("🈁", "koko"),
    ("🛂", "passport control"),
    ("🚱", "non-potable water"),
    ("🚟", "suspension railway"),
    ("🛄", "baggage claim"),
    ("🚳", "no bicycles"),
    ("☠", "skull and crossbones"),
    ("🤗", "hugging face"),
    ("🤔", "thinking face"),
    ("🤓", "nerd face"),
    ("🤐", "zipper mouth face"),
    ("🙄", "face with rolling eyes"),
    ("🙃", "upside down face"),
    ("🙂", "slightly smiling face"),
    ("🖕", "middle finger"),
    ("✍", "writing hand"),
    ("🕶", "dark sunglasses"),
    ("👁‍🗨", "eye speachbubble"),
    ("👁", "eye"),
    ("🏋🏿‍♀", "weightlifter woman darktone"),
    ("🏋🏾‍♀", "weightlifter woman mediumdarktone"),
    ("🏋🏽‍♀", "weightlifter woman mediumtone"),
    ("🏋🏼‍♀", "weightlifter woman mediumlighttone"),
    ("🏋🏻‍♀", "weightlifter woman lighttone"),
    ("🏋‍♀", "weightlifter woman"),
    ("🏋🏿", "weightlifter darktone"),
    ("🏋🏾", "weightlifter mediumdarktone"),
    ("🏋🏽", "weightlifter mediumtone"),
    ("🏋🏼", "weightlifter mediumlighttone"),
    ("🏋🏻", "weightlifter lighttone"),
    ("🏋", "weightlifter"),
    ("⛹🏿‍♀", "basketballer woman darktone"),
    ("⛹🏾‍♀", "basketballer woman mediumdarktone"),
    ("⛹🏽‍♀", "basketballer woman mediumtone"),
    ("⛹🏼‍♀", "basketballer woman mediumlighttone"),
    ("⛹🏻‍♀", "basketballer woman lighttone"),
    ("⛹‍♀", "basketballer woman"),
    ("⛹🏿", "basketballer darktone"),
    ("⛹🏾", "basketballer mediumdarktone"),
    ("⛹🏽", "basketballer mediumtone"),
    ("⛹🏼", "basketballer mediumlighttone"),
    ("⛹🏻", "basketballer lighttone"),
    ("⛹", "basketballer"),
    ("🕴", "Man in Suit Levitating"),
    ("🏌", "golfer"),
    ("🏌‍♀", "golfer woman"),
    ("*️⃣", "asterisk"),
    ("❣️", "heart exclamation"),
    ("✡️", "star of david"),
    ("✝️", "cross"),
    ("⚜", "fleur-de-lis"),
    ("⚛", "atom"),
    ("☸", "wheel of dharma"),
    ("☯", "yin yang"),
    ("☮", "peace"),
    ("☪", "star and crescent"),
    ("☦", "orthodox cross"),
    ("☣", "biohazard"),
    ("☢", "radioactive"),
    ("🛐", "place of worship"),
    ("🗯", "anger right"),
    ("🕎", "menorah"),
    ("🕉", "om symbol"),
    ("⚰", "coffin"),
    ("⚙", "gear"),
    ("⚗", "alembic"),
    ("⚖", "scales"),
    ("⚔", "crossed swords"),
    ("⌨", "keyboard"),
    ("🛡", "shield"),
    ("🛏", "bed"),
    ("🛍", "shopping bags"),
    ("🛌", "sleeping accommodation"),
    ("🗳", "ballot box"),
    ("🗜", "compression"),
    ("🗑", "wastebasket"),
    ("🗄", "file cabinet"),
    ("🖲", "trackball"),
    ("🖨", "printer"),
    ("🕹", "joystick"),
    ("🕳", "hole"),
    ("🕯", "candle"),
    ("📿", "prayer beads"),
    ("📸", "camera with flash"),
    ("🏺", "amphora"),
    ("🏷", "label"),
    ("🏴", "waving black flag"),
    ("🏳", "waving white flag"),
    ("🎞", "film frames"),
    ("🎛", "control knobs"),
    ("🎚", "level slider"),
    ("🌡", "thermometer"),
    ("🛬", "airplane arriving"),
    ("🛫", "airplane departure"),
    ("🛤", "railway track"),
    ("🛣", "motorway"),
    ("🕍", "synagogue"),
    ("🕌", "mosque"),
    ("🕋", "kaaba"),
    ("🏟", "stadium"),
    ("🏜", "desert"),
    ("🏛", "classical building"),
    ("🏙", "cityscape"),
    ("🏕", "camping"),
    ("🏹", "bow and arrow"),
    ("🏵", "rosette"),
    ("🏐", "volleyball"),
    ("🏅", "medal"),
    ("🎗", "reminder ribbon"),
    ("🍿", "popcorn"),
    ("🍾", "champagne"),
    ("🌶", "hot pepper"),
    ("🌯", "burrito"),
    ("🌮", "taco"),
    ("🌭", "hotdog"),
    ("☘", "shamrock"),
    ("☄", "comet"),
    ("🦃", "turkey"),
    ("🦂", "scorpion"),
    ("🦁", "lion face"),
    ("🦀", "crab"),
    ("🕸", "spider web"),
    ("🕷", "spider"),
    ("🐿", "chipmunk"),
    ("🌬", "wind blowing face"),
    ("🌫", "fog"),
    ("⏯", "play pause"),
    ("⏮", "track previous"),
    ("⏭", "track next"),
    ("⛱", "beach umbrella"),
    ("⛓", "chains"),
    ("⛏", "pick"),
    ("⏱", "stopwatch"),
    ("⛴", "ferry"),
    ("⛰", "mountain"),
    ("⛩", "shinto shrine"),
    ("⛸", "ice skate"),
    ("⛷", "skier"),
    ("🇦🇨", "Ascension Island"),
    ("🇦🇩", "Andorra"),
    ("🇦🇪", "United Arab Emirates"),
    ("🇦🇫", "Afghanistan"),
    ("🇦🇬", "Antigua and Barbuda"),
    ("🇦🇮", "Anguilla"),
    ("🇦🇱", "Albania"),
    ("🇦🇲", "Armenia"),
    ("🇦🇴", "Angola"),
    ("🇦🇶", "Antarctica"),
    ("🇦🇷", "Argentina"),
    ("🇦🇸", "American Samoa"),
    ("🇦🇹", "Austria"),
    ("🇦🇺", "Australia"),
    ("🇦🇼", "Aruba"),
    ("🇦🇽", "Åland Islands"),
    ("🇦🇿", "Azerbaijan"),
    ("🇧🇦", "Bosnia and Herzegovina"),
    ("🇧🇧", "Barbados"),
    ("🇧🇩", "Bangladesh"),
    ("🇧🇪", "Belgium"),
    ("🇧🇫", "Burkina Faso"),
    ("🇧🇬", "Bulgaria"),
    ("🇧🇭", "Bahrain"),
    ("🇧🇮", "Burundi"),
    ("🇧🇯", "Benin"),
    ("🇧🇱", "St. Barthélemy"),
    ("🇧🇲", "Bermuda"),
    ("🇧🇳", "Brunei"),
    ("🇧🇴", "Bolivia"),
    ("🇧🇶", "Caribbean Netherlands"),
    ("🇧🇷", "Brazil"),
    ("🇧🇸", "Bahamas"),
    ("🇧🇹", "Bhutan"),
    ("🇧🇻", "Bouvet Island"),
    ("🇧🇼", "Botswana"),
    ("🇧🇾", "Belarus"),
    ("🇧🇿", "Belize"),
    ("🇨🇦", "Canada"),
    ("🇨🇨", "Cocos (Keeling) Islands"),
    ("🇨🇩", "Congo - Kinshasa"),
    ("🇨🇫", "Central African Republic"),
    ("🇨🇬", "Congo - Brazzaville"),
    ("🇨🇭", "Switzerland"),
    ("🇨🇮", "Côte d'Ivoire"),
    ("🇨🇰", "Cook Islands"),
    ("🇨🇱", "Chile"),
    ("🇨🇲", "Cameroon"),
    ("🇨🇳", "China"),
    ("🇨🇴", "Colombia"),
    ("🇨🇵", "Clipperton Island"),
    ("🇨🇷", "Costa Rica"),
    ("🇨🇺", "Cuba"),
    ("🇨🇻", "Cape Verde"),
    ("🇨🇼", "Curaçao"),
    ("🇨🇽", "Christmas Island"),
    ("🇨🇾", "Cyprus"),
    ("🇨🇿", "Czech Republic"),
    ("🇩🇪", "Germany"),
    ("🇩🇬", "Diego Garcia"),
    ("🇩🇯", "Djibouti"),
    ("🇩🇰", "Denmark"),
    ("🇩🇲", "Dominica"),
    ("🇩🇴", "Dominican Republic"),
    ("🇩🇿", "Algeria"),
    ("🇪🇦", "Ceuta and Melilla"),
    ("🇪🇨", "Ecuador"),
    ("🇪🇪", "Estonia"),
    ("🇪🇬", "Egypt"),
    ("🇪🇭", "Western Sahara"),
    ("🇪🇷", "Eritrea"),
    ("🇪🇸", "Spain"),
    ("🇪🇹", "Ethiopia"),
    ("🇪🇺", "European Union"),
    ("🇫🇮", "Finland"),
    ("🇫🇯", "Fiji"),
    ("🇫🇰", "Falkland Islands"),
    ("🇫🇲", "Micronesia"),
    ("🇫🇴", "Faroe Islands"),
    ("🇫🇷", "France"),
    ("🇬🇦", "Gabon"),
    ("🇬🇧", "United Kingdom"),
    ("🇬🇩", "Grenada"),
    ("🇬🇪", "Georgia"),
    ("🇬🇫", "French Guiana"),
    ("🇬🇬", "Guernsey"),
    ("🇬🇭", "Ghana"),
    ("🇬🇮", "Gibraltar"),
    ("🇬🇱", "Greenland"),
    ("🇬🇲", "Gambia"),
    ("🇬🇳", "Guinea"),
    ("🇬🇵", "Guadeloupe"),
    ("🇬🇶", "Equatorial Guinea"),
    ("🇬🇷", "Greece"),
    ("🇬🇸", "South Georgia and South Sandwich Islands"),
    ("🇬🇹", "Guatemala"),
    ("🇬🇺", "Guam"),
    ("🇬🇼", "Guinea-Bissau"),
    ("🇬🇾", "Guyana"),
    ("🇭🇰", "Hong Kong SAR China"),
    ("🇭🇲", "Heard and McDonald Islands"),
    ("🇭🇳", "Honduras"),
    ("🇭🇷", "Croatia"),
    ("🇭🇹", "Haiti"),
    ("🇭🇺", "Hungary"),
    ("🇮🇨", "Canary Islands"),
    ("🇮🇩", "Indonesia"),
    ("🇮🇪", "Ireland"),
    ("🇮🇱", "Israel"),
    ("🇮🇲", "Isle of Man"),
    ("🇮🇳", "India"),
    ("🇮🇴", "British Indian Ocean Territory"),
    ("🇮🇶", "Iraq"),
    ("🇮🇷", "Iran"),
    ("🇮🇸", "Iceland"),
    ("🇮🇹", "Italy"),
    ("🇯🇪", "Jersey"),
    ("🇯🇲", "Jamaica"),
    ("🇯🇴", "Jordan"),
    ("🇯🇵", "Japan"),
    ("🇰🇪", "Kenya"),
    ("🇰🇬", "Kyrgyzstan"),
    ("🇰🇭", "Cambodia"),
    ("🇰🇮", "Kiribati"),
    ("🇰🇲", "Comoros"),
    ("🇰🇳", "St. Kitts and Nevis"),
    ("🇰🇵", "North Korea"),
    ("🇰🇷", "South Korea"),
    ("🇰🇼", "Kuwait"),
    ("🇰🇾", "Cayman Islands"),
    ("🇰🇿", "Kazakhstan"),
    ("🇱🇦", "Laos"),
    ("🇱🇧", "Lebanon"),
    ("🇱🇨", "St. Lucia"),
    ("🇱🇮", "Liechtenstein"),
    ("🇱🇰", "Sri Lanka"),
    ("🇱🇷", "Liberia"),
    ("🇱🇸", "Lesotho"),
    ("🇱🇹", "Lithuania"),
    ("🇱🇺", "Luxembourg"),
    ("🇱🇻", "Latvia"),
    ("🇱🇾", "Libya"),
    ("🇲🇦", "Morocco"),
    ("🇲🇨", "Monaco"),
    ("🇲🇩", "Moldova"),
    ("🇲🇪", "Montenegro"),
    ("🇲🇫", "St. Martin"),
    ("🇲🇬", "Madagascar"),
    ("🇲🇭", "Marshall Islands"),
    ("🇲🇰", "Macedonia"),
    ("🇲🇱", "Mali"),
    ("🇲🇲", "Myanmar (Burma)"),
    ("🇲🇳", "Mongolia"),
    ("🇲🇴", "Macau SAR China"),
    ("🇲🇵", "Northern Mariana Islands"),
    ("🇲🇶", "Martinique"),
    ("🇲🇷", "Mauritania"),
    ("🇲🇸", "Montserrat"),
    ("🇲🇹", "Malta"),
    ("🇲🇺", "Mauritius"),
    ("🇲🇻", "Maldives"),
    ("🇲🇼", "Malawi"),
    ("🇲🇽", "Mexico"),
    ("🇲🇾", "Malaysia"),
    ("🇲🇿", "Mozambique"),
    ("🇳🇦", "Namibia"),
    ("🇳🇨", "New Caledonia"),
    ("🇳🇪", "Niger"),
    ("🇳🇫", "Norfolk Island"),
    ("🇳🇬", "Nigeria"),
    ("🇳🇮", "Nicaragua"),
    ("🇳🇱", "Netherlands"),
    ("🇳🇴", "Norway"),
    ("🇳🇵", "Nepal"),
    ("🇳🇷", "Nauru"),
    ("🇳🇺", "Niue"),
    ("🇳🇿", "New Zealand"),
    ("🇴🇲", "Oman"),
    ("🇵🇦", "Panama"),
    ("🇵🇪", "Peru"),
    ("🇵🇫", "French Polynesia"),
    ("🇵🇬", "Papua New Guinea"),
    ("🇵🇭", "Philippines"),
    ("🇵🇰", "Pakistan"),
    ("🇵🇱", "Poland"),
    ("🇵🇲", "St. Pierre and Miquelon"),
    ("🇵🇳", "Pitcairn Islands"),
    ("🇵🇷", "Puerto Rico"),
    ("🇵🇸", "Palestinian Territories"),
    ("🇵🇹", "Portugal"),
    ("🇵🇼", "Palau"),
    ("🇵🇾", "Paraguay"),
    ("🇶🇦", "Qatar"),
    ("🇷🇪", "Réunion"),
    ("🇷🇴", "Romania"),
    ("🇷🇸", "Serbia"),
    ("🇷🇺", "Russia"),
    ("🇷🇼", "Rwanda"),
    ("🇸🇦", "Saudi Arabia"),
    ("🇸🇧", "Solomon Islands"),
    ("🇸🇨", "Seychelles"),
    ("🇸🇩", "Sudan"),
    ("🇸🇪", "Sweden"),
    ("🇸🇬", "Singapore"),
    ("🇸🇭", "St. Helena"),
    ("🇸🇮", "Slovenia"),
    ("🇸🇯", "Svalbard and Jan Mayen"),
    ("🇸🇰", "Slovakia"),
    ("🇸🇱", "Sierra Leone"),
    ("🇸🇲", "San Marino"),
    ("🇸🇳", "Senegal"),
    ("🇸🇴", "Somalia"),
    ("🇸🇷", "Suriname"),
    ("🇸🇸", "South Sudan"),
    ("🇸🇹", "São Tomé and Prí­ncipe"),
    ("🇸🇻", "El Salvador"),
    ("🇸🇽", "Sint Maarten"),
    ("🇸🇾", "Syria"),
    ("🇸🇿", "Swaziland"),
    ("🇹🇦", "Tristan da Cunha"),
    ("🇹🇨", "Turks and Caicos Islands"),
    ("🇹🇩", "Chad"),
    ("🇹🇫", "French Southern Territories"),
    ("🇹🇬", "Togo"),
    ("🇹🇭", "Thailand"),
    ("🇹🇯", "Tajikistan"),
    ("🇹🇰", "Tokelau"),
    ("🇹🇱", "Timor-Leste"),
    ("🇹🇲", "Turkmenistan"),
    ("🇹🇳", "Tunisia"),
    ("🇹🇴", "Tonga"),
    ("🇹🇷", "Turkey"),
    ("🇹🇹", "Trinidad and Tobago"),
    ("🇹🇻", "Tuvalu"),
    ("🇹🇼", "Taiwan"),
    ("🇹🇿", "Tanzania"),
    ("🇺🇦", "Ukraine"),
    ("🇺🇬", "Uganda"),
    ("🇺🇲", "U.S. Outlying Islands"),
    ("🇺🇸", "United States"),
    ("🇺🇾", "Uruguay"),
    ("🇺🇿", "Uzbekistan"),
    ("🇻🇦", "Vatican City"),
    ("🇻🇨", "St. Vincent and Grenadines"),
    ("🇻🇪", "Venezuela"),
    ("🇻🇬", "British Virgin Islands"),
    ("🇻🇮", "U.S. Virgin Islands"),
    ("🇻🇳", "Vietnam"),
    ("🇻🇺", "Vanuatu"),
    ("🇼🇫", "Wallis and Futuna"),
    ("🇼🇸", "Samoa"),
    ("🇽🇰", "Kosovo"),
    ("🇾🇪", "Yemen"),
    ("🇾🇹", "Mayotte"),
    ("🇿🇦", "South Africa"),
    ("🇿🇲", "Zambia"),
    ("🇿🇼", "Zimbabwe"),
    ("🖤", "black heart"),
    ("🗨", "speech left"),
    ("🥚", "egg"),
    ("🛑", "octagonal sign"),
    ("♠", "spades"),
    ("♥", "hearts"),
    ("♦", "diamonds"),
    ("♣", "clubs"),
    ("🥁", "drum"),
    ("↔", "left right arrow"),
    ("©", "copyright"),
    ("®", "registered"),
    ("™", "tm"),
    ("0️⃣", "0"),
    ("1️⃣", "1"),
    ("2️⃣", "2"),
    ("3️⃣", "3"),
    ("4️⃣", "4"),
    ("5️⃣", "5"),
    ("6️⃣", "6"),
    ("7️⃣", "7"),
    ("8️⃣", "8"),
    ("9️⃣", "9"),
    ("#⃣", "hash"),
    ("*⃣", "asterisk"),
    ("0⃣", "zero"),
    ("1⃣", "one"),
    ("2⃣", "two"),
    ("3⃣", "three"),
    ("4⃣", "four"),
    ("5⃣", "five"),
    ("6⃣", "six"),
    ("7⃣", "seven"),
    ("8⃣", "eight"),
    ("9⃣", "nine"),
];
